@startuml

class FilterOutputStream
class FileOutputStream
class BufferedOutputStream
class DataOutputStream
interface OutputStream

interface OutputStream{
+write()
}

class FileOutputStream{
+write()
}

class FilterOutputStream{
FilterOutputStream(OutputStream outputStream)
+write()
}

class BufferedOutputStream{
//增加缓冲功能
}

class DataOutputStream{
+writeInt(int c)
}


OutputStream <|-.- FileOutputStream
OutputStream <|-.- FilterOutputStream
FilterOutputStream <|-- BufferedOutputStream
FilterOutputStream <|-- DataOutputStream



@enduml